services:
  nginx:
    image: nginx:latest
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    depends_on:
      - order-service
      - invoice-service

  order-service:
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DEBUG: order-service:*

  invoice-service:
    command: npm run start:dev
    environment:
      NODE_ENV: development
      DEBUG: invoice-service:*

  # Development-specific database configurations
  order-db:
    command: mongod --logpath /dev/null # Reduce log verbosity in development

  invoice-db:
    command: mongod --logpath /dev/null # Reduce log verbosity in development

  # Development-specific RabbitMQ configurations
  rabbitmq:
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,error}]
